<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:macro name = "base_link" params="base_mass base_length base_width base_height">
        <link name="base_link">
            <visual>
                <geometry>
                    <box size="${base_length} ${base_width} ${base_height}"/>
                </geometry>
                <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0"/>
                <material name="blue"/>
            </visual>
            <collision>
                <geometry>
                    <box size="${base_length} ${base_width} ${base_height}"/>
                </geometry>
                <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0"/>
            </collision>
            <inertial>
                <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0"/>
                <mass value="${base_mass}"/>
                <inertia ixx="${base_mass * (base_width * base_width + base_height * base_height) / 12}"
                        ixy="0" ixz="0"
                        iyy="${base_mass * (base_length * base_length + base_height * base_height) / 12}"
                        iyz="0"
                        izz="${base_mass * (base_length * base_length + base_width * base_width) / 12}"/>
            </inertial>
        </link>
    </xacro:macro>

    <xacro:macro name = "wheel_link" params="prefix wheel_mass wheel_radius wheel_length">
        <link name="${prefix}_wheel_link">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="1.5708 0 0"/>
                <material name="grey"/>
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="1.5708 0 0"/>
            </collision>
            <inertial>
                <mass value="${wheel_mass}"/>
                <inertia ixx="${(wheel_mass / 12) * (3 * wheel_radius * wheel_radius + wheel_length * wheel_length)}"
                        ixy="0" ixz="0"
                        iyy="${(wheel_mass / 12) * (3 * wheel_radius * wheel_radius + wheel_length * wheel_length)}"
                        iyz="0"
                        izz="${(wheel_mass / 12) * (3 * wheel_radius * wheel_radius + wheel_length * wheel_length)}"/>
            </inertial>
        </link>
    </xacro:macro>

    <xacro:macro name = "base_inertia" params="mass x y z">
        <mass value = "${mass}" />
        <inertia
            ixx="${mass * (y*y + z*z) / 12}"
            iyy="${mass * (x*x + z*z) / 12}"
            izz="${mass * (x*x + y*y) / 12}" />
    </xacro:macro>

    <xacro:macro name = "wheel_inertia" params = "m r h xyz rpy">
        <inertial>
            <origin xyz = "${xyz}" rpy = "${rpy}" />
            <mass value = "${m}" />
            <inertia ixx = "${(m/12) * (3*r*r + h*h)}" ixy = "0" ixz = "0"
            iyy = "${(m/12) * (3*r*r + h*h)}" iyz = "0"
            izz = "${(m/12) * (3*r*r + h*h)}"/>
        </inertial>
    </xacro:macro>
    
    <xacro:macro name = "base_joint">
        <joint name="base_joint" type="fixed">
            <parent link="base_footprint"/>
            <child link="base_link"/>
            <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
        </joint>
    </xacro:macro>

    <xacro:macro name = "wheel_joint" params="prefix x y z">
        <joint name="${prefix}_wheel_joint" type="continuous">
            <parent link="base_link"/>
            <child link="${prefix}_wheel_link"/>
            <origin xyz="${x} ${y} ${z}" rpy="0 0 0"/>
            <axis xyz="0 1 0"/>
        </joint>    
    </xacro:macro>
</robot>