<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:macro name = "base_macro" params="base_mass base_length base_width base_height">
        <link name="base_link">
            <visual>
                <geometry>
                    <box size="${base_length} ${base_width} ${base_height}"/>
                </geometry>
                <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0"/>
                <material name="blue"/>
            </visual>
            <collision>
                <geometry>
                    <box size="${base_length} ${base_width} ${base_height}"/>
                </geometry>
                <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0"/>
            </collision>
            <xacro:box_inertia m="5.0" l="${2*base_length}" w="${2*base_width}" h="${2*base_height}" xyz="0 0 ${base_height / 2.0}" rpy="0 0 0"/>         
        </link>
    </xacro:macro>

    <xacro:macro name = "wheel_link" params="prefix wheel_mass wheel_radius wheel_length">
        <link name="${prefix}_wheel_link">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="1.5708 0 0"/>
                <material name="grey"/>
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="1.5708 0 0"/>
            </collision>
            <xacro:wheel_inertia m = "1.0" r = "${2*wheel_radius}" h = "${2*wheel_length}" xyz="0 0 0" rpy="1.5708 0 0"/>
        </link>
    </xacro:macro>
    
    <xacro:macro name = "box_inertia" params = "m l w h xyz rpy">
        <inertial>
            <origin xyz = "${xyz}" rpy = "${rpy}" />
            <mass value = "${m}" />
            <inertia ixx = "${(m/12) * (l*l+h*h)}" ixy = "0" ixz = "0"
            iyy = "${(m/12) * (l*l+h*h)}" iyz = "0"
            izz = "${(m/12) * (l*l+h*h)}"/>
        </inertial>
    </xacro:macro>

    <xacro:macro name = "wheel_inertia" params = "m r h xyz rpy">
        <inertial>
            <origin xyz = "${xyz}" rpy = "${rpy}" />
            <mass value = "${m}" />
            <inertia ixx = "${(m/12) * (3*r*r + h*h)}" ixy = "0" ixz = "0"
            iyy = "${(m/12) * (3*r*r + h*h)}" iyz = "0"
            izz = "${(m/12) * (3*r*r + h*h)}"/>
        </inertial>
    </xacro:macro>
    
    <xacro:macro name = "base_joint">
        <joint name="base_joint" type="fixed">
            <parent link="base_footprint"/>
            <child link="base_link"/>
            <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
        </joint>
    </xacro:macro>

    <xacro:macro name = "wheel_joint" params="prefix x y z">
        <joint name="${prefix}_wheel_joint" type="revolute">
            <parent link="base_link"/>
            <child link="${prefix}_wheel_link"/>
            <origin xyz="${x} ${y} ${z}" rpy="0 0 0"/>
            <axis xyz="0 1 0"/>
            <limit effort="100" velocity="10" lower="0" upper="3.14"/>
        </joint>    
    </xacro:macro>
</robot>