<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename = "/home/tayya/four_wheel_ws/src/four_wheel_vehicle/urdf/common_properties.xacro"/>

    <xacro:property name="base_mass" value="5.0"/>
    <xacro:property name="base_length" value="0.6" />
    <xacro:property name="base_width" value="0.4" />
    <xacro:property name="base_height" value="0.2" />

    <xacro:property name="wheel_mass" value="1.0" />
    <xacro:property name="wheel_radius" value="0.1" />
    <xacro:property name="wheel_length" value="0.05" />

    <material name="blue">
        <color rgba="0 0 0.5 1"/>
    </material>
    
    <material name="grey">
        <color rgba="0.5 0.5 0.5 1"/>
    </material>

    <material name = "orange">
        <color rgba="1.0 0.5 0 1" />
    </material>

    <material name = "yellow">
        <color rgba="1.0 1.0 0 1" />
    </material>

    <link name="base_footprint"/>
    
    <xacro:base_macro base_mass="${base_mass}" base_length = "${base_length}" base_width = "${base_width}" base_height = "${base_height}"/>
    
    <xacro:wheel_link prefix = "front_left"  wheel_mass = "${wheel_mass}" wheel_radius = "${wheel_radius}" wheel_length="${wheel_length}"/>
    <xacro:wheel_link prefix = "front_right" wheel_mass = "${wheel_mass}" wheel_radius = "${wheel_radius}" wheel_length="${wheel_length}"/>
    <xacro:wheel_link prefix = "rear_left"   wheel_mass = "${wheel_mass}" wheel_radius = "${wheel_radius}" wheel_length="${wheel_length}"/>
    <xacro:wheel_link prefix = "rear_right"  wheel_mass = "${wheel_mass}" wheel_radius = "${wheel_radius}" wheel_length="${wheel_length}"/>

    <xacro:base_joint/>
 
    <joint name="front_left_wheel_joint" type="revolute">
        <parent link="base_link"/>
        <child link="front_left_wheel_link"/>
        <origin xyz="${base_length / 2.5} ${(base_width / 2.0) + (wheel_length / 2.0)} 0" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
        <limit effort="100" velocity="10" lower="0" upper="3.14"/>
    </joint>

    <joint name="front_right_wheel_joint" type="revolute">
        <parent link="base_link"/>
        <child link="front_right_wheel_link"/>
        <origin xyz="${base_length / 2.5} -${(base_width / 2.0) + (wheel_length / 2.0)} 0" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
        <limit effort="100" velocity="10" lower="0" upper="3.14"/>
    </joint>

    <joint name="rear_left_wheel_joint" type="revolute">
        <parent link="base_link"/>
        <child link="rear_left_wheel_link"/>
        <origin xyz="-${base_length / 2.5} ${(base_width / 2.0) + (wheel_length / 2.0)} 0" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
        <limit effort="100" velocity="10" lower="0" upper="3.14"/>
    </joint>

    <joint name="rear_right_wheel_joint" type="revolute">
        <parent link="base_link"/>
        <child link="rear_right_wheel_link"/>
        <origin xyz="-${base_length / 2.5} -${(base_width / 2.0) + (wheel_length / 2.0)} 0" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
        <limit effort="100" velocity="10" lower="0" upper="3.14"/>
    </joint>



</robot>
