controller_manager:
  ros__parameters:
    update_rate: 10  # Hz
    use_sim_time: true

    forward_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    forward_position_controller:
      type: position_controllers/JointGroupPositionController

forward_position_controller:
  ros__parameters:
    joints:
      - front_left_wheel_holder_joint
      - rear_left_wheel_holder_joint
      - front_right_wheel_holder_joint
      - rear_right_wheel_holder_joint
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position

forward_velocity_controller:
  ros__parameters:
    joints:
      - front_left_wheel_holder_joint
      - rear_left_wheel_holder_joint
      - front_right_wheel_holder_joint
      - rear_right_wheel_holder_joint
      - front_left_wheel_joint
      - rear_left_wheel_joint
      - front_right_wheel_joint
      - rear_right_wheel_joint
    interface_name: velocity
    command_interfaces:
      - velocity
    state_interfaces:
      - velocity